from typing import Any, ClassVar
from ..lib.camera_utils import RenderSizes
from ..exporting.obj_export import MeshData, PointCloudData
from ..exporting.hair_export import HairData
from ..exporting.instancer_export import InstancerData
from ..exporting.smoke_export import SmokeData

withDR2: bool
withProfiling: bool

class AttrPlugin:
    plugin: str
    output: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class CosmosAssetSettings:
    assetType: str
    isAnimated: bool
    lightFile: str
    luminaireFile: str
    # The settings.json manifest of a Chaos Cosmos Asset Set; set only for assetType "AssetSet".
    settingsFile: str
    # Non-empty only for a member of an Asset Set: the token passed to importCosmosAsset()
    # for this member, echoed back so it can be matched to its manifest instance.
    setInstanceToken: str
    locationsMap: dict[str, str]
    matFile: str
    objFile: str
    packageId: str
    revisionId: int
    # The asset's name in the Cosmos browser. Empty falls back to naming by plugin / file name.
    assetName: str
    planeWidth: float
    planeHeight: float
    applyTriplanarMapping: bool
    texRealWorldWidth: float
    texRealWorldHeight: float
    # Drag-and-drop origin fields. When hasDropCoords is False the asset was
    # imported via the Cosmos browser's Import button and the fields below
    # should be ignored.
    hasDropCoords: bool
    worldX: float
    worldY: float
    worldZ: float
    dropTargetObject: str
    # Specific material-slot index for Material drops, or -1 for the
    # default policy (clear and append to slot 0).
    dropTargetSlot: int
    # Surface normal at the hit point (valid only when hasHitNormal is True
    # AND the drop ray hit geometry - not on a ground-plane fallback).
    hasHitNormal: bool
    normalX: float
    normalY: float
    normalZ: float
    # Cosmos surface-attachment tag: "" (default), "wall", or "ceiling".
    # When non-empty AND hasHitNormal is True the Python side pre-rotates
    # the imported asset so its attachment side faces the drop surface.
    surfaceAttachment: str
    # Set when Ctrl was held during the drop. The Python side aligns the
    # asset's local +Z to the hit surface normal even for assets that
    # wouldn't otherwise be re-oriented.
    forceNormalAlign: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class VrsceneImportResult:
    status: int         # 0 Ok, 1 ParseError, 2 Cancelled, 3 InternalError
    errorText: str
    errorFile: str
    errorLine: int
    pluginCount: int
    paramCount: int
    sceneBaseDir: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ExportSceneSettings:
    cloudExport: bool
    compressed: bool
    filePath: str
    hexArrays: bool
    hexTransforms: bool
    hostAppString: str
    pluginTypes: str
    separateFiles: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ProxyExportSettings:
    animOn: bool
    elementsPerVoxel: int
    endFrame: int
    filePath: str
    previewFaces: int
    previewType: int
    startFrame: int
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ExporterSettings:
    closeVfbOnStop: bool
    drHosts: list[str]
    drRenderOnlyOnHosts: bool
    drUse: bool
    exporterType: int
    previewDir: str
    profilerMaxDepth: int
    profilerMode: int
    profilerOutputDirectory: str
    profilerSceneName: str
    remoteDispatcher: str
    renderThreads: int
    separateFiles: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def setDRHosts(cls, hosts: list[str]) -> None: ...

class HostInfo:
    blenderVersion: str
    buildVersion: str
    vrayVersion: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class MeshExportOptions:
    forceDynamicGeometry: bool
    mergeChannelVerts: bool
    useSubsurfToOSD: bool
    def __init__(cls, *args, **kwargs) -> None: ...

class OSLParam:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(cls): ...
    @property
    def isOutputSocket(self): ...
    @property
    def name(self): ...
    @property
    def socketDefaultValue(self): ...
    @property
    def socketType(self): ...

class Subdiv:
    enabled: bool
    level: int
    type: int
    useCreases: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ViewSettings:
    renderMode: int
    vfbFlags: int
    viewportImageQuality: int
    viewportImageType: int
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ZmqServerArgs:
    __instance_size__: ClassVar[int] = ...
    appSDKPath: str
    blenderPID: int
    blenderVersion: str
    dumpLogFile: str
    exePath: str
    headlessMode: bool
    licenseType: str
    logLevel: int
    enableQtLogs: bool
    noHeartbeat: bool
    pluginVersion: str
    port: int
    vfbSettingsFile: str
    vrayLibPath: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

def abortRender(renderer: int) -> Any: ...
def calculateDownloadSize(packageId: str, revisionId: int, missingTextures: list[str]): ...
def checkScannedLicense() -> None: ...
def clearFrameData(renderer: int, upToTime: float) -> None: ...
def clearScene(renderer: int) -> None: ...
def clearMainBitmapCache() -> None: ...
def clearVfbImage() -> None: ...
def updateLightingAnalysis() -> None: ...
def closeVFB() -> None: ...
def continueRenderSequence(renderer: int) -> None: ...
def getMainRenderer(settings: ExporterSettings) -> int: ...
def releaseMainRenderer(renderer: int) -> None: ...
def createPreviewRenderer(settings: ExporterSettings) -> int: ...
def deletePreviewRenderer(renderer: int) -> None: ...
def downloadMissingAssets() -> None: ...
def importCosmosAsset(assetNames: list[str], applyTriplanarMapping: bool = False, applyRealWorldScale: bool = False, instanceTokens: list[str] = []) -> None: ...
def cosmosDropImport(packageId: str, revisionId: int, worldX: float, worldY: float, worldZ: float, dropTargetObject: str, dropTargetSlot: int, hasHitNormal: bool, normalX: float, normalY: float, normalZ: float, applyTriplanar: bool, applyRealWorldScale: bool, forceNormalAlign: bool) -> None: ...
def encodeScannedParameters(materialId: int, nodeName: str, paramsJson: str) -> None: ...
def endStatsCollection(renderer: int, printStats: bool, title: str) -> None: ...
def exit() -> None: ...
def exportGeometry(renderer: int, meshData: MeshData, asyncExport: bool) -> None: ...
def exportHair(renderer: int, hairData: HairData) -> None: ...
def exportInstancer(renderer: int, instancerData: InstancerData) -> None: ...
def exportJobIsRunning(renderer: int) -> bool: ...
def exportPointCloud(renderer: int, pointCloudData: PointCloudData, asyncExport: bool) -> None: ...
def exportProxyFile(renderer: int, proxySettings: ProxyExportSettings) -> tuple[bool, str]: ...
def exportSmoke(renderer: int, smokeData: SmokeData) -> None: ...
def finishExport(renderer: int, interactive: bool) -> None: ...
def getEngineUpdateMessage(renderer: int) -> str: ...
def getImage(renderer: int) -> object: ...
def getMetadata(renderer: int, key: str) -> str: ...
def getPluginPropertyValues(renderer: int) -> list[tuple[str, str, object]]: ...   # (pluginName, propertyName, value)
def getReceivedImagesCount(renderer: int) -> int: ...
def getLastRenderedFrame(renderer: int) -> int: ...
def getOslScriptParameters(script: str) -> list: ...
def getRenderPassImage(renderer: int, passName: str) -> object: ...
def getRenderProgress(renderer: int) -> float: ...
def getRenderStage() -> tuple[str, float]: ...
def getImportedVrscene(importId: int, largeAttrs: dict[str, list[str]] = {}) -> list[tuple[str, str, dict[str, object], list[str]]]: ...
def hasLicense() -> bool: ...
def isCommunityEdition() -> bool: ... # Monkey patched at runtime
def imageWasUpdated(renderer: int) -> bool: ...
def importVrsceneStart(filePath: str, skipDefaults: bool = True, frameStart: float = 0.0, frameEnd: float = 0.0, typeFilter: str = "") -> int: ...
def importVrsceneCancel(importId: int) -> None: ...
def importVrsceneRelease(importId: int) -> None: ...
def init(logFile: str) -> None: ...
def isInitialized() -> bool: ...
def isRenderReady(renderer: int) -> bool: ...
def isRunning() -> bool: ...
def log(msg: str, level: int, raw: bool) -> None: ...
def openCollaboration(hostInfo: HostInfo) -> None: ...
def openCosmos(browserPage: int) -> None: ...
def openVFB() -> None: ...
def openVFBWithRenderer(renderer: int) -> None: ...
def openVerasWithViewport(imagePath: str) -> None: ...
def openVerasWithVfbImage() -> None: ...
def pluginCreate(renderer: int, name: str, pluginType: str, allowTypeChange = False) -> None: ...
def pluginRemove(renderer: int, name: str) -> None: ...
def pluginResetValue(renderer: int, name: str, attrName: str) -> None: ...
def pluginReCreateAttr(renderer: int, name: str, attrName: str, animatable: bool) -> None: ...
def pluginUpdateAColor(renderer: int, pluginName: str, attrName: str, r: float, g: float, b: float, a: float, animatable: bool) -> None: ...
def pluginUpdateColor(renderer: int, pluginName: str, attrName: str, r: float, g: float, b: float, animatable: bool) -> None: ...
def pluginUpdateFloat(renderer: int, pluginName: str, attrName: str, val: float, animatable: bool) -> None: ...
def pluginUpdateFloatList(*renderer: int, pluginName: str, attrName: str, floatList: list[float], animatable: bool) -> None: ...
def pluginUpdateVectorList(renderer: int, pluginName: str, attrName: str, floats: object, animatable: bool = True) -> None: ...
def pluginUpdateInt(renderer: int, pluginName: str, attrName: str, val: int, animatable: bool) -> None: ...
def pluginUpdateIntList(renderer: int, pluginName: str, attrName: str, intList: list[int], animatable: bool) -> None: ...
def pluginUpdateIntVector(renderer: int, pluginName: str, attrName: str, x: int, y: int, z: int, animatable: bool) -> None: ...
def pluginUpdateList(renderer: int, pluginName: str, attrName: str, objList: list, listElemType: str, animatable: bool) -> None: ...
def pluginUpdateMatrix(renderer: int, pluginName: str, attrName: str, mat: object, animatable: bool) -> None: ...
def pluginUpdatePluginDesc(renderer: int, pluginName: str, attrName: str, value: AttrPlugin, animatable: bool, forceUpdate: bool) -> None: ...
def pluginUpdatePluginList(renderer: int, pluginName: str, attrName: str, pluginList: list[AttrPlugin], animatable: bool) -> None: ...
def pluginUpdateString(renderer: int, pluginName: str, attrName: str, val: str, animatable: bool) -> None: ...
def pluginUpdateStringList(renderer: int, pluginName: str, attrName: str, strList: list[str]) -> None: ...
def pluginUpdateTransform(renderer: int, pluginName: str, attrName: str, transform: object, animatable: bool) -> None: ...
def pluginUpdateVector(renderer: int, pluginName: str, attrName: str, x: float, y: float, z: float, animatable: bool) -> None: ...
def renderEnd(renderer: int) -> None: ...
def renderFrame(renderer: int) -> None: ...
def renderJobIsRunning(renderer: int) -> bool: ...
def renderSequenceStart(renderer: int, sequence: list[int]) -> None: ...
def renderStart(renderer: int, renderResultPtr: int, onImageUpdated: object, imageToBlender: bool = True) -> None: ...
def requestRenderChannel(renderer: int, channelType: int, pluginInstanceName: str = "", subIndex: int = 0) -> None: ...
def setElementPasses(renderer: int, passes: list[tuple[int, int, str, int]]) -> None: ...
def requestComputeDevices() -> None: ...
def resetVfbToolbar() -> None: ...
def setVfbRenderRegion(x: int, y: int, width: int, height: int, imgWidth: int, imgHeight: int, enabled: bool) -> None: ...
def setAppUpdateRequestCallback(callback: object) -> None: ...
def setAutoUpdateChangedCallback(callback: object) -> None: ...
def setCameraName(renderer: int, cameraName: str): ...
def setResumableRendering(renderer: int, enabled: bool, outputFileName: str = "", autosaveSeconds: int = 0, deleteOnSuccess: bool = False) -> None: ...
def setComputeDevices(deviceIds: list[int], deviceType: int) -> None: ...
def setCosmosDownloadAssets(callback: object) -> None: ...
def setCosmosDownloadSize(callback: object) -> None: ...
def setCosmosImportCallback(callback: object) -> None: ...
def setVrsceneImportProgressCallback(callback: object) -> None: ...    # callback(importId, pluginsDone, pluginsTotal, stage)
def setVrsceneImportFinishedCallback(callback: object) -> None: ...    # callback(importId, result: VrsceneImportResult)
def setLogLevel(level: int, enableQtLogs: bool) -> None: ...
def setRenderFrame(renderer: int, frame: float) -> None: ...
def setRenderSizes(renderer: int, sizeData: RenderSizes) -> None: ...
def setRenderStartCallback(callback: object) -> None: ...
def setSwitchLicenseToCommunityCallback(switchLicenseToCommunityCallback: object) -> None: ...
def setRenderStoppedCallback(renderer: int, callback: object) -> None: ...
def setScannedLicenseCallback(callback: object) -> None: ...
def setScannedParamBlockCallback(callback: object) -> None: ...
def setTelemetryState(anonymousState: str, personalyzedState: str) -> None: ...
def setUpdateComputeDevicesCallback(callback: object) -> None: ...
def setVfbLayers(layers: str) -> None: ...
def setVfbLayersUpdateCallback(callback: object) -> None: ...
def setVfbOnTop(alwaysOnTop: bool) -> None: ...
def setVfbOnTopWithRenderer(renderer: int, alwaysOnTop: bool) -> None: ...
def setVfbRenderRegionChangedCallback(callback: object) -> None: ...
def setVfbSettingsUpdateCallback(callback: object) -> None: ...
def setAddRenderElementToSceneCallback(addRenderElementCallback: object) -> None: ...
def setVfbShowMessagesWindowCallback(vfbShowMessagesWindowCallback: object) -> None: ...
def setZmqServerAbortCallback(callback: object) -> None: ...
def showUserDialog(json: str) -> None: ...
def scatterPreviewStart() -> int: ...
def scatterPreviewStop() -> None: ...
def requestScatterPreview(renderer: int, requestId: int, scatterPluginName: str, time: float = 0.0) -> None: ...
def cancelScatterPreview(renderer: int, requestId: int) -> None: ...
def setScatterPreviewCallback(callback: object) -> None: ...
def scatterPreviewGetResult(requestId: int) -> tuple: ...
def scatterPreviewReleaseResult(requestId: int) -> None: ...
def requestScatterPreset(renderer: int, requestId: int, filePath: str, unitRescale: float = 1.0) -> None: ...
def setScatterPresetCallback(callback: object) -> None: ...
def scatterPresetGetResult(requestId: int) -> tuple: ...
def scatterPresetReleaseResult(requestId: int) -> None: ...
def start(structVRayForBlender: ZmqServerArgs) -> None: ...
def startExport(renderer: int, threadCount: int) -> None: ...
def startStatsCollection(renderer: int) -> None: ...
def stop() -> None: ...
def syncViewSettings(renderer: int, viewSettings: ViewSettings) -> None: ...
def updateScenePath(scenePath: str) -> None: ...
def writeVrscene(renderer: int, settings: ExportSceneSettings) -> int: ...
