from typing import Any, ClassVar
from ..lib.camera_utils import RenderSizes
from ..exporting.obj_export import MeshData, PointCloudData
from ..exporting.hair_export import HairData
from ..exporting.instancer_export import InstancerData
from ..exporting.smoke_export import SmokeData

withDR2: bool

class AttrPlugin:
    plugin: str
    output: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class CosmosAssetSettings:
    assetType: str
    isAnimated: bool
    lightFile: str
    locationsMap: dict[str, str]
    matFile: str
    objFile: str
    packageId: str
    revisionId: int
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ExportSceneSettings:
    cloudExport: bool
    compressed: bool
    filePath: str
    hexArrays: bool
    hexTransforms: bool
    hostAppString: str
    pluginTypes: str
    separateFiles: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ExporterSettings:
    closeVfbOnStop: bool
    drHosts: list[str]
    drRenderOnlyOnHosts: bool
    drUse: bool
    exporterType: int
    previewDir: str
    remoteDispatcher: str
    renderThreads: int
    separateFiles: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def setDRHosts(cls, hosts: list[str]) -> None: ...

class HostInfo:
    blenderVersion: str
    buildVersion: str
    vrayVersion: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class MeshExportOptions:
    forceDynamicGeometry: bool
    mergeChannelVerts: bool
    useSubsurfToOSD: bool
    def __init__(cls, *args, **kwargs) -> None: ...

class OSLParam:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(cls): ...
    @property
    def isOutputSocket(self): ...
    @property
    def name(self): ...
    @property
    def socketDefaultValue(self): ...
    @property
    def socketType(self): ...

class Subdiv:
    enabled: bool
    level: int
    type: int
    useCreases: bool
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ViewSettings:
    renderMode: int
    vfbFlags: int
    viewportImageQuality: int
    viewportImageType: int
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

class ZmqServerArgs:
    __instance_size__: ClassVar[int] = ...
    appSDKPath: str
    blenderPID: int
    blenderVersion: str
    dumpLogFile: str
    exePath: str
    headlessMode: bool
    logLevel: int
    enableQtLogs: bool
    noHeartbeat: bool
    pluginVersion: str
    port: int
    vfbSettingsFile: str
    vrayLibPath: str
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...

def abortRender(renderer: int) -> Any: ...
def calculateDownloadSize(packageId: str, revisionId: int, missingTextures: list[str]): ...
def checkScannedLicense() -> None: ...
def clearFrameData(renderer: int, upToTime: float) -> None: ...
def clearScene(renderer: int) -> None: ...
def closeVFB() -> None: ...
def continueRenderSequence(renderer: int) -> None: ...
def getMainRenderer(settings: ExporterSettings) -> int: ...
def createPreviewRenderer(settings: ExporterSettings) -> int: ...
def deletePreviewRenderer(renderer: int) -> None: ...
def downloadMissingAssets() -> None: ...
def encodeScannedParameters(materialId: int, nodeName: str, paramsJson: str) -> None: ...
def endStatsCollection(renderer: int, printStats: bool, title: str) -> None: ...
def exit() -> None: ...
def exportGeometry(renderer: int, meshData: MeshData, asyncExport: bool) -> None: ...
def exportHair(renderer: int, hairData: HairData) -> None: ...
def exportInstancer(renderer: int, instancerData: InstancerData) -> None: ...
def exportJobIsRunning(renderer: int) -> None: ...
def exportPointCloud(renderer: int, pointCloudData: PointCloudData) -> None: ...
def exportSmoke(renderer: int, smokeData: SmokeData) -> None: ...
def finishExport(renderer: int, interactive: bool) -> None: ...
def getEngineUpdateMessage(renderer: int) -> str: ...
def getImage(renderer: int) -> object: ...
def getLastRenderedFrame(renderer: int) -> int: ...
def getOslScriptParameters(script: str) -> list: ...
def getRenderPassImage(renderer: int, passName: str) -> object: ...
def getRenderProgress(renderer: int) -> float: ...
def hasLicense() -> bool: ...
def imageWasUpdated(renderer: int) -> bool: ...
def init(logFile: str) -> None: ...
def isInitialized() -> bool: ...
def isRenderReady(renderer: int) -> bool: ...
def isRunning() -> bool: ...
def log(msg: str, level: int, raw: bool) -> None: ...
def openCollaboration(hostInfo: HostInfo) -> None: ...
def openCosmos(browserPage: int) -> None: ...
def openVFB() -> None: ...
def openVFBWithRenderer(renderer: int) -> None: ...
def pluginCreate(renderer: int, name: str, pluginType: str, allowTypeChange = False) -> None: ...
def pluginRemove(renderer: int, name: str) -> None: ...
def pluginResetValue(renderer: int, name: str, attrName: str) -> None: ...
def pluginReCreateAttr(renderer: int, name: str, attrName: str, animatable: bool) -> None: ...
def pluginUpdateAColor(renderer: int, pluginName: str, attrName: str, r: float, g: float, b: float, a: float, animatable: bool) -> None: ...
def pluginUpdateColor(renderer: int, pluginName: str, attrName: str, r: float, g: float, b: float, animatable: bool) -> None: ...
def pluginUpdateFloat(renderer: int, pluginName: str, attrName: str, val: float, animatable: bool) -> None: ...
def pluginUpdateFloatList(*renderer: int, pluginName: str, attrName: str, floatList: list[float], animatable: bool) -> None: ...
def pluginUpdateInt(renderer: int, pluginName: str, attrName: str, val: int, animatable: bool) -> None: ...
def pluginUpdateIntList(renderer: int, pluginName: str, attrName: str, intList: list[int], animatable: bool) -> None: ...
def pluginUpdateIntVector(renderer: int, pluginName: str, attrName: str, x: int, y: int, z: int, animatable: bool) -> None: ...
def pluginUpdateList(renderer: int, pluginName: str, attrName: str, objList: list, listElemType: str, animatable: bool) -> None: ...
def pluginUpdateMatrix(renderer: int, pluginName: str, attrName: str, mat: object, animatable: bool) -> None: ...
def pluginUpdatePluginDesc(renderer: int, pluginName: str, attrName: str, value: AttrPlugin, animatable: bool, forceUpdate: bool) -> None: ...
def pluginUpdatePluginList(renderer: int, pluginName: str, attrName: str, pluginList: list[AttrPlugin], animatable: bool) -> None: ...
def pluginUpdateString(renderer: int, pluginName: str, attrName: str, val: str, animatable: bool) -> None: ...
def pluginUpdateStringList(renderer: int, pluginName: str, attrName: str, strList: list[str]) -> None: ...
def pluginUpdateTransform(renderer: int, pluginName: str, attrName: str, transform: object, animatable: bool) -> None: ...
def pluginUpdateVector(renderer: int, pluginName: str, attrName: str, x: float, y: float, z: float, animatable: bool) -> None: ...
def renderEnd(renderer: int) -> None: ...
def renderFrame(renderer: int) -> None: ...
def renderJobIsRunning(renderer: int) -> bool: ...
def renderSequenceStart(renderer: int, start: int, end: int, step: int) -> None: ...
def renderStart(renderer: int, renderResultPtr: int, onImageUpdated: object) -> None: ...
def requestComputeDevices() -> None: ...
def resetVfbToolbar() -> None: ...
def setCameraName(renderer: int, cameraName: str): ...
def setComputeDevices(deviceIds: list[int], deviceType: int) -> None: ...
def setCosmosDownloadAssets(callback: object) -> None: ...
def setCosmosDownloadSize(callback: object) -> None: ...
def setCosmosImportCallback(callback: object) -> None: ...
def setLogLevel(level: int, enableQtLogs: bool) -> None: ...
def setRenderFrame(renderer: int, frame: float) -> None: ...
def setRenderSizes(renderer: int, sizeData: RenderSizes) -> None: ...
def setRenderStartCallback(callback: object) -> None: ...
def setRenderStoppedCallback(renderer: int, callback: object) -> None: ...
def setScannedLicenseCallback(callback: object) -> None: ...
def setScannedParamBlockCallback(callback: object) -> None: ...
def setTelemetryState(anonymousState: str, personalyzedState: str) -> None: ...
def setUpdateComputeDevicesCallback(callback: object) -> None: ...
def setVfbLayers(layers: str) -> None: ...
def setVfbLayersUpdateCallback(callback: object) -> None: ...
def setVfbOnTop(alwaysOnTop: bool) -> None: ...
def setVfbOnTopWithRenderer(renderer: int, alwaysOnTop: bool) -> None: ...
def setVfbSettingsUpdateCallback(callback: object) -> None: ...
def setZmqServerAbortCallback(callback: object) -> None: ...
def showUserDialog(json: str) -> None: ...
def start(structVRayForBlender: ZmqServerArgs) -> None: ...
def startExport(renderer: int, threadCount: int) -> None: ...
def startStatsCollection(renderer: int) -> None: ...
def stop() -> None: ...
def syncViewSettings(renderer: int, viewSettings: ViewSettings) -> None: ...
def updateCosmosSceneName(sceneName: str) -> None: ...
def writeVrscene(renderer: int, settings: ExportSceneSettings) -> int: ...
