set(APPSDK_XPAK_VERSION "72009.20260128" )

set(QT_XPAK "AppSDKQT6")
if (WIN32)
	set(QT_XPAK_VERSION "6.5.3.1002" )
else()
	set(QT_XPAK_VERSION "6.5.3.1001" )
endif()
set(RAPIDJSON_XPAK_VERSION "1.1.0.1001" )

if (APPLE)
	set(GRPC_XPAK_VERSION 1.41.1000)
elseif (UNIX)
	set(GRPC_XPAK_VERSION 1.22.1002)
else()
	set(GRPC_XPAK_VERSION 1.22.1001)
endif()

# BLENDER_SDK_XPAK_VERSION is the version of the Blender_SDK xpak
# BLENDER_SDK_VER is the version of the Blender SDK files included in the Blender_SDK pack (corresponding to the 'blender_x.y' folder)

set(BLENDER_SDK_XPAK_VERSION "1002" )

if (BLENDER_VER STREQUAL "4.2")
	set(BLENDER_SDK_XPAK "Blender_SDK_4_2" )
elseif(BLENDER_VER STREQUAL "4.3")
	set(BLENDER_SDK_XPAK "Blender_SDK_4_2" )
elseif(BLENDER_VER STREQUAL "4.4")
	set(BLENDER_SDK_XPAK "Blender_SDK_4_4" )
elseif(BLENDER_VER STREQUAL "4.5")
	set(BLENDER_SDK_XPAK "Blender_SDK_4_4" )
elseif(BLENDER_VER STREQUAL "5.0")
	set(BLENDER_SDK_XPAK "Blender_SDK_5_0" )
else()
	message(FATAL_ERROR "Invalid BLENDER_VER '${BLENDER_VER}'")
endif()
