# Plugins which are not skipped for import/conversion purposes or plugins that were simply hidden from
# the menus but should still remain active and just not show up in node creation menus.
HIDDEN_PLUGINS = (
    "TexFresnel",
    "Float3ToAColor",
    "TexBlend",
    "TexColorCorrect",
    "TexVectorProduct",
    "TexVectorToColor",
    "TexUVW",
    "UVWGenObjectBBox",
    "TexNormalMapFlip",
    "TexBlendBumpNormal",
    "TexCondition2"
)

# Plugins for which node generation and
# visualization in the UI is not required
SKIPPED_PLUGINS = (
    # 'Virtual' plugins
    'SettingsCameraGlobal',

    # not meant to be used
    'MtlSingleBRDF',
    'BRDFSkinComplex',
    'BSDFPointParticle',
    'MtlStreakFade',

    # 3ds max specific
    'TexMaxHairInfo',
    'GeomHair',
    'TexMaskMax',
    'TexMarbleMax',
    'TexRGBTintMax',

    # XSI specific
    'TexBillboardParticle',
    'TexColor2Scalar',
    'TexColor8Mix',
    'TexColorAverage',
    'TexColorCurve',
    'TexColorExponential',
    'TexColorMathBasic',
    'TexColorSwitch',
    'TexDisplacacementRestrict',
    'TexFloatPerVertexHairSampler',
    'TexHairRootSampler',
    'TexInterpLinear',
    'TexParticleShape',
    'TexPerVertexHairSampler',
    'texRenderHair',
    'TexRgbaCombine',
    'TexRgbaSplit',
    'TexScalarCurve',
    'TexScalarExponential',
    'TexScalarHairRootSampler',
    'TexScalarMathBasic',
    'TexSurfIncidence',
    'TexXSIBitmap',
    'TexXSICell',
    'texXSIColor2Alpha',
    'texXSIColor2Vector',
    'TexXSIColorBalance',
    'TexXSIColorCorrection',
    'TexXSIColorMix',
    'TexXSIFabric',
    'TexXSIFalloff',
    'TexXSIFlagstone',
    'TexXSIGradient',
    'TexXSIHLSAdjust',
    'TexXSIIntensity',
    'TexXSILayered',
    'TexXSIMulti',
    'TexXSINormalMap',
    'TexXSIRGBAKeyer',
    'TexXSIRipple',
    'TexXSIRock',
    'TexXSIScalar2Color',
    'TexXSIScalarInvert',
    'TexXSISnow',
    'TexXSIVein',
    'TexXSIVertexColorLookup',
    'TexXSIWeightmapColorLookup',
    'TexXSIWeightmapLookup',
    'TexXSIWood',
    'volumeXSIMulti',
    'xsiUVWGenChannel',
    'xsiUVWGenEnvironment',

    # Handled with meta node
    'TexBitmap',
    'BitmapBuffer',

    # Manually handled
    'TexBezierCurve',
    'GeomMayaHair',
    'GeomStaticMesh',
    'VRayScene',
    'EnvFogMeshGizmo',

    # Unused
    'MtlBump',
    'GeomImagePlane',
    'GeomInfinitePlane',
    'TexCustomBitmap',
    'TexMultiX',
    'TexIDIntegerMap',
    'TexMeshVertexColor',
    'TexMeshVertexColorWithDefault',
    'TexMultiProjection',
    'TexParticleDiffuse',
    'TexParticleShape',
    'TexParticleId',
    'RawBitmapBuffer',
    'VolumeScatterFog',

    # Houdini specific
    'TexExtMaterialID',
    'TexExtMapChannels',

    # Not yet implemented
    'TexRamp',

    # Not useful
    "TexAColor",
    "TexBerconDistortion",
    "TexBerconGrad",
    "TexBerconNoise",
    "TexBerconTile",
    "TexBerconWood",
    "TexBifrostVVMix",
    "TexGradient",
    "TexICC",
    "TexInt",
    "TexLut",
    "TexMotionOcclusion",
    "TexMultiFloat",
    "TexNoise",
    "TexNoiseMaya",
    "TexC4DNoise",
    "TexPtex",
    "TexRaySwitch",
    "TexSimplexNoise",
    "TexStencil",
    "TexThickness",
    "Outputs the UVW from a UVWGen plugin as RGB color",
    "TexVoxelData",
    "TexWater",
    "ColorCorrect",
    "ColorTextureToMono",
    "FloatToTex",
    "TexAColorChannel",
    "TexColorAndAlpha",
    "TexColorCondition",
    "TexColorConstant",
    "TexColorLogic",
    "TexColorMask",
    "TexCombineColor",
    "TexCombineColorLightMtl",
    "TexCombineFloat",
    "TexCompMax",
    "TexComposite",
    "TexIntToFloat",
    "TexMaxGamma",
    "TexPlusMinusAverage",
    "TexRGBMultiplyMax",
    "TexSurfaceLuminance",
    "TexSwitch",
    "TexSwitchFloat",
    "TexSwitchInt",
    "TexSwitchMatrix",
    "TexSwitchTransform",
    "TexTemperatureToColor",
    "TexUVWGenToTexture",
    "TexVectorOp",
    "TexVertexColorDirect",
    "TransformToTex",

    # Could be used in future
    "TexCondition",
    "TexSnow",
    "PhxShaderOceanTex",
    "PhxShaderTex",
    "PhxShaderTexAlpha",
    "ParticleTex",
    "TexMeshVertexColorChannel",
    "TexDistanceBetween",
    "TexOSL",

    # Unused UVWGen nodes
    "UVWGenBercon",
    "UVWGenSwitch",

    # Currently unsupported effects
    "PhxShaderSimVol",
    "PhxShaderSim",
    "PhxShaderCache",
    "SphereFade",
    "SphereFadeGizmo",
    "VolumeChannels",
    "VolumeMulti",

    # Unsupported misc plugins
    "ColorMapperTest",
    "CustomGlsl",
    "NURBSCurve",
    "PhxShaderFoam",
    "PhxShaderPGroup",
    "PhxShaderPrtLoader",
    "SceneModifierTest",
    "TexMayaFluidCombined",
    "TexMayaFluidProcedural",
    "TexModoSampler",
    "TexParticleSampler",
    "TexVRayFurSampler",
    "TrimmingRegion",
    "TrimmingRegionsComplex",

    # To be re-implemented
    "TexOpenVDB",
    "MtlGLSL",
    "MtlOSL"
)


MANUALLY_CREATED_PLUGINS = (
    'TexLayeredMax',
    'TexOSL',
    'MtlOSL',
    'MtlMulti',
    'RenderChannelColor',
    'RenderChannelDenoiser'
)